server:
  port: 9999

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service

      client:
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_EXTERNAL_URL}/realms/leilao-service/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service/protocol/openid-connect/certs
            user-name-attribute: sub
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway
            client-secret: ${KEYCLOAK_CLIENT_SECRET_API_GATEWAY}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: ${KEYCLOAK_REDIRECT_URL}/login/oauth2/code/keycloak

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: false
    fetch-registry: true

resilience4j.circuitbreaker:
  metrics:
    enabled: true
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000ms
      permittedNumberOfCallsInHalfOpenState: 3
      registerHealthIndicator: true

resilience4j.timelimiter:
  metrics:
    enabled: true
  configs:
    default:
      timeoutDuration: 5s

logging:
  level:
    br.com.infnet.api_gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.server.mvc.filter.TokenRelayFilterFunctions: DEBUG
    org.springframework.web.servlet.function.support.RouterFunctionMapping: DEBUG

    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.web: DEBUG

    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.web.filter: DEBUG
    io.github.resilience4j: DEBUG

    io.micrometer: INFO