server:
  port: 9999

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service

      client:
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_EXTERNAL_URL}/realms/leilao-service/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service/protocol/openid-connect/token
            user-info-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service/protocol/openid-connect/userinfo
            jwk-set-uri: ${KEYCLOAK_INTERNAL_URL}/realms/leilao-service/protocol/openid-connect/certs
            user-name-attribute: sub
        registration:
          keycloak:
            provider: keycloak
            client-id: api-gateway
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"


  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: gateway-health
              uri: forward:/actuator/health
              predicates:
                - Path=/health

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10000ms
      permittedNumberOfCallsInHalfOpenState: 3

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.server.mvc.filter.TokenRelayFilterFunctions: DEBUG
    org.springframework.web.servlet.function.support.RouterFunctionMapping: DEBUG